//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSanBong
{
    using System;
    using System.Collections.Generic;
    
    public partial class THIET_BI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THIET_BI()
        {
            this.BAO_TRI = new HashSet<BAO_TRI>();
        }
    
        public string MaThietBi { get; set; }
        public string TenThietBi { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string Loai { get; set; }
        public string MaSan { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAO_TRI> BAO_TRI { get; set; }
        public virtual SAN_BONG SAN_BONG { get; set; }
    }
}
