//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSanBong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAO_TRI
    {
        public string MaBaoTri { get; set; }
        public string MaThietBi { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public string LoaiBaoTri { get; set; }
        public Nullable<decimal> ChiPhi { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string NhanVienBT { get; set; }
    
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
        public virtual THIET_BI THIET_BI { get; set; }
    }
}
