//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSanBong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICH_DAT_SAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICH_DAT_SAN()
        {
            this.THANH_TOAN = new HashSet<THANH_TOAN>();
        }
    
        public string MaDatSan { get; set; }
        public string MaSan { get; set; }
        public string MaKH { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public string MaNV { get; set; }
    
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
        public virtual SAN_BONG SAN_BONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THANH_TOAN> THANH_TOAN { get; set; }
    }
}
