//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSanBong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANH_TOAN
    {
        public string MaTT { get; set; }
        public string MaDat { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public Nullable<System.DateTime> NgayTT { get; set; }
        public string GhiChu { get; set; }
        public string MaNV { get; set; }
    
        public virtual LICH_DAT_SAN LICH_DAT_SAN { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
